services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=dukldriver
    command: redis-server --requirepass dukldriver --appendonly yes
    volumes:
      - ~/data/redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dukldriver
      - MONGO_INITDB_DATABASE=dukl
    command: mongod --auth
    volumes:
      - ~/data/mongo:/data/db